# Generated by Django 3.0.3 on 2020-04-13 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='shelves',
            field=models.ManyToManyField(null=True, to='main.Shelf'),
        ),
        migrations.AddField(
            model_name='shelf',
            name='lib',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Library'),
        ),
    ]
