# Generated by Django 3.0.3 on 2020-04-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200413_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='shelves',
            field=models.ManyToManyField(to='main.Shelf'),
        ),
    ]
