# Generated by Django 3.0.5 on 2020-04-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200413_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='author', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.CharField(default=2, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='dfd', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='title', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='year_pub',
            field=models.CharField(default=2012, max_length=4),
            preserve_default=False,
        ),
    ]
