# Generated by Django 3.0.5 on 2020-04-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200414_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='shelves',
            field=models.ManyToManyField(null=True, to='main.Shelf'),
        ),
    ]
