# Generated by Django 3.0.5 on 2020-04-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200414_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='shelves',
            field=models.ManyToManyField(blank=True, to='main.Shelf'),
        ),
    ]
