# Generated by Django 3.0.5 on 2020-04-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200414_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='name',
            field=models.CharField(default='shelf', max_length=256),
        ),
    ]
